# Generated by Django 5.1.7 on 2025-03-24 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nlp_tools', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tool',
        ),
    ]
