# Generated by Django 5.1.7 on 2025-03-24 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_category_parent_remove_profile_institution_and_more'),
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Institution',
        ),
    ]
